[custom.all.json]
type   = "local"
path   = "."
ipkg   = "json.ipkg"
test   = "test/test.ipkg"

[custom.all.json-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.json-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.elab-util]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:fixity_lam"
ipkg   = "elab-util.ipkg"

[custom.all.sop]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-sop"
commit = "latest:fixity_lam"
ipkg   = "sop.ipkg"

[custom.all.pretty-show]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-pretty-show"
commit = "latest:fixity_lam"
ipkg   = "pretty-show.ipkg"

[custom.all.hedgehog]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-hedgehog"
commit = "latest:main"
ipkg   = "hedgehog.ipkg"

[custom.all.elab-pretty]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-elab-util"
commit = "latest:fixity_lam"
ipkg   = "elab-pretty.ipkg"

[custom.all.parser]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-parser"
commit = "latest:main"
ipkg   = "parser.ipkg"
